### ISSUE TITLE
Pin 23 missing in list.

### ISSUE THREAD

**Issue by f34rdotcom** [hatlabs/sh-esp32#4]
I see GPIO23 on the GPIO header but not in the list.
  https://github.com/hatlabs/sh-esp32/blame/main/pages/hardware.md#L266

**Comment by mairas** [comment]
Thanks! Will fix.

In general, all comments and improvement suggestions for the documentation are much appreciated!

**Comment by mairas** [comment]
Fixed in PR #5.
